aviary:
  prompt_template: "aviary/aviary_b1_without_inputs.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4"
    max_tokens: 2048
    temperature: 0.9
  fn_completion_parser: "ranking_parser"
  batch_size: 1
