basic_text_davinci_003:
  prompt_templates:
    with_inputs: "text-davinci-003/basic_b1_with_inputs.txt"
    without_inputs: "text-davinci-003/basic_b1_without_inputs.txt"
  fn_decoder: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-4-0314"
    max_tokens: 50
    temperature: 0
  outputs_to_match:
    1: '(?:^|\n) ?Output \(a\)'
    2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
