vicuna:
  prompt_templates:
    without_inputs: "vicuna/vicuna.txt"
  fn_completions: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-4"
    max_tokens: 1024
    temperature: 0.2
  fn_completion_parser: "vicuna_parser"
  batch_size: 1
