basic_gpt4:
  prompt_templates:
    with_inputs: "alpaca_farm/chatml_b1_chat_with_inputs.txt"
    without_inputs: "alpaca_farm/chatml_b1_chat_without_inputs.txt"
  fn_completions: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-4"
    max_tokens: 20
    temperature: 0
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Output \(a\)'
      2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
