basic_oasst_pythia_12b:
  prompt_templates:
    with_inputs: "oasst-pythia-12b/basic_b1_with_inputs.txt"
    without_inputs: "oasst-pythia-12b/basic_b1_without_inputs.txt"
  fn_decoder: "huggingface_local_completions"
  decoder_kwargs:
    model_name: "OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5"
    max_new_tokens: 50
  outputs_to_match:
    1: '(?:^|\n) ?Output \(a\)'
    2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
