aviary:
  prompt_templates:
    with_inputs: "aviary/aviary_b1_with_inputs.txt"
    without_inputs: "aviary/aviary_b1_without_inputs.txt"
  fn_completions: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-4"
    max_tokens: 2048
    temperature: 0.9
  fn_completion_parser: "aviary_parser"
  batch_size: 1
