lmsys:
  prompt_template: "lmsys/lmsys_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4"
    max_tokens: 1024
    temperature: 0.2
  fn_completion_parser: "lmsys_parser"
  batch_size: 1
