gpt4_ranking:
  prompt_templates:
    with_inputs: "gpt4_ranking/ranking_b1_with_inputs.txt"
    without_inputs: "gpt4_ranking/ranking_b1_without_inputs.txt"
  fn_completions: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-4"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "aviary_parser"
  batch_size: 1
