# paths are relative to configs

basic_guanaco_33b:
  prompt_templates:
    with_inputs: "guanaco-33b/basic_b1_with_inputs.txt"
    without_inputs: "guanaco-33b/basic_b1_without_inputs.txt"
  fn_decoder: "huggingface_api_completions" # use "huggingface_local_completions" if you want local serving
  decoder_kwargs:
    model_name: "timdettmers/guanaco-33b-merged"
    max_new_tokens: 30
  outputs_to_match:
    1: '(?:^|\n) ?Output \(a\)'
    2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
