# paths are relative to configs

opt_125m:
  prompt_templates:
    with_inputs: "opt_125m/zeroshot_b1_with_inputs.txt"
    without_inputs: "opt_125m/zeroshot_b1_without_inputs.txt"
  fn_decoder: "huggingface_local_completions"
  decoder_kwargs:
    model_name: "facebook/opt-125m"
    max_new_tokens: 50
  outputs_to_match:
    1: '(?:^|\n)Output \(a\)'
    2: '(?:^|\n)Output \(b\)'
  batch_size: 1
