opt_125m:
  prompt_template: "opt_125m/zeroshot_b1_without_inputs.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "facebook/opt-125m"
    max_new_tokens: 50
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n)Output \(a\)'
      2: '(?:^|\n)Output \(b\)'
  batch_size: 1
