cohere:
  prompt_templates:
    with_inputs: "gpt3/basic_b1_with_inputs.txt"
    without_inputs: "gpt3/basic_b1_without_inputs.txt"
  fn_completions: "cohere_completions"
  decoder_kwargs:
    model_name: "command"
    max_tokens: 50
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Output \(a\)'
      2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
