falcon_40b_instruct:
  prompt_template: "falcon_40b_instruct/basic_prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "tiiuae/falcon-40b-instruct"
    max_new_tokens: 50
    trust_remote_code: True
    model_kwargs:
      torch_dtype: 'bfloat16'
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Output \(a\)'
      2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
