claude_ranking:
  prompt_templates:
    with_inputs: "claude_ranking/ranking_b1_with_inputs.txt"
    without_inputs: "claude_ranking/ranking_b1_without_inputs.txt"
  fn_completions: "anthropic_completions"
  decoder_kwargs:
    model_name: "claude-v1"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "aviary_parser"
  batch_size: 1
