alpaca_farm_ppo_human_7b:
  prompt_template: "alpaca_farm_ppo_human_7b/basic_prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./alpaca_farm_ppo_human" # weight diff merged from https://huggingface.co/tatsu-lab/alpaca-farm-ppo-human-wdiff
    max_new_tokens: 50
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Output \(a\)'
      2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
