# paths are relative to auto_annotations

basic_chatgpt:
  prompt_templates:
    with_inputs: "chatgpt/basic_b1_with_inputs.txt"
    without_inputs: "chatgpt/basic_b1_without_inputs.txt"
  fn_completions: "openai_completions"
  decoder_kwargs:
    model_name: "gpt-3.5-turbo-0301"
    max_tokens: 50
    temperature: 0
  outputs_to_match:
    1: '(?:^|\n) ?Output \(a\)'
    2: '(?:^|\n) ?Output \(b\)'
  batch_size: 1
